create table task (
  id integer generated by default as identity primary key,
  task_name text not null,
  display_number integer not null
);

create table task_history (
  id integer generated by default as identity primary key,
  task_id integer not null,
  datetime timestamp with time zone not null,
  foreign key (task_id) references task(id) on delete cascade
);
